/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `recetas`;
CREATE TABLE `recetas` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ingredientes` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `preparacion` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `categoria_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `recetas_user_id_foreign` (`user_id`),
  KEY `recetas_categoria_id_foreign` (`categoria_id`),
  CONSTRAINT `recetas_categoria_id_foreign` FOREIGN KEY (`categoria_id`) REFERENCES `categoria_recetas` (`id`),
  CONSTRAINT `recetas_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `recetas` (`id`, `titulo`, `ingredientes`, `preparacion`, `imagen`, `user_id`, `categoria_id`, `created_at`, `updated_at`) VALUES
(1, 'Helado de fresa', '<div>dsgfj.</div>', '<div>fghf</div>', 'images/recetas/nXNvUFTyfUtbLlcWxpnduKv1Wku03SDGlcm45LEx.jpeg', 2, 4, '2020-09-03 09:27:31', '2020-09-04 08:48:48');
INSERT INTO `recetas` (`id`, `titulo`, `ingredientes`, `preparacion`, `imagen`, `user_id`, `categoria_id`, `created_at`, `updated_at`) VALUES
(2, 'Conitos hawaianos', '<ul><li>2 (52g) tortillas de harina de trigo, partidas a la mitad</li><li>1 (14g) cucharada mantequilla</li><li>1 (4g) tira de apio, finamente picado</li><li>1/2 (37g) pimentón pequeño rojo sin semillas y, finamente picado</li><li>4 (68g) tajadas de jamón cortadas, en tiras delgadas</li><li>4 (60) cucharadas de CREMA DE LECHE NESTLE®</li><li>½ (3g) cucharadita de NATURISIMO MAGGI®</li><li>2 (60g) melocotones en almíbar cortados, en trozos medianos.</li></ul><div><br></div>', '<div><strong>PASO 1</strong></div><div>Envolver cada media tortilla tratando de formar un cono y cerrar con un palillo.</div><div><strong>PASO 2</strong></div><div>En una sartén a fuego medio derretir la mantequilla e incorporar el apio y el pimentón, cocinar por 2 minutos y añadir el jamón, revolver para integrar. Agregar el NATURISIMO MAGGI®, la CREMA DE LECHE NESTLÉ®, y el melocotón cortado en trozos pequeños.</div><div><strong>PASO 3</strong></div><div>Rellenar cada conito con la mezcla teniendo cuidado que no se desarmen. Servir.</div><div><br></div>', 'images/recetas/QYExwNg08gN3r0V8t5cfHdeCzd5vsUT0w5f4WVOV.jpeg', 1, 2, '2020-09-03 09:48:28', '2020-09-04 08:45:27');
INSERT INTO `recetas` (`id`, `titulo`, `ingredientes`, `preparacion`, `imagen`, `user_id`, `categoria_id`, `created_at`, `updated_at`) VALUES
(3, 'Postre de las tres leches', '<ul><li>10 (75g) galletas SALTINAS DORÉ®</li><li>1 (320g) doy pack de LECHE CONDENSADA LA LECHERA®</li><li>1 (295g) lata grande de CREMA DE LECHE NESTLÉ®</li><li>½ (125ml) taza de leche</li><li>1 (7g) sobre de gelatina sin sabor</li><li>2 cucharadas de agua tibia</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>En una refractaria o molde mediano armar una base con la mitad de las galletas SALTINAS DORÉ®.</div><div><strong>PASO 2</strong><br>En el vaso de la licuadora adicionar; la LECHE CONDENSADA LA LECHERA®, la CREMA DE LECHE NESTLÉ® y la leche.<br>Aparte en un recipiente disolver la gelatina sin sabor en las dos cucharadas de agua tibia, con la ayuda de un tenedor mezclar hasta disolver bien y no tenga grumos.</div><div><strong>PASO 3</strong><br>Adicionar la gelatina al vaso de la licuadora y licuar por 20 segundos o hasta integrar bien. Bañar las galletas con la mitad de la mezcla de las tres leches, encima poner la otra mitad de las galletas DORÉ® y, por último, bañar las galletas con la mezcla de las tres leches restante.</div><div><strong>PASO 4</strong><br>Llevar el molde al refrigerador por 1 hora aproximadamente o hasta que el postre de las tres leches esté firme.<br>Pasado el tiempo de frío, retirar el postre de la nevera y servir.</div><div><br></div>', 'images/recetas/qDE1spuY1fBVOaQjpQN7BZqwC8LjMmX8mPKMADKL.jpeg', 1, 4, '2020-09-03 09:49:55', '2020-09-04 08:46:20');
INSERT INTO `recetas` (`id`, `titulo`, `ingredientes`, `preparacion`, `imagen`, `user_id`, `categoria_id`, `created_at`, `updated_at`) VALUES
(4, 'Arroz con pollo', '<ul><li>1 (453g) pechuga de pollo sin piel</li><li>1 (9g) sobre de CALDO DE GALLINA MAGGI® Desmenuzado</li><li>1 litro de agua fría</li><li>2 (28g) cucharadas de aceite</li><li>1/2 (42g) cebolla cabezona mediana finamente picada</li><li>2 (246g) tomates rojos finamente picados sin piel y sin semilla</li><li>1/2 (37g) pimentón rojo finamente picado</li><li>1 (3g) diente de ajo finamente picado</li><li>1/4 (125g) de libra de arveja</li><li>1 (50g) zanahoria pequeña pelada y cortada en cubos pequeños</li><li>1/2 (3g) cucharadita de NATURISIMO MAGGI®</li><li>½ (250g) libra de arroz</li><li>1½ tazas de líquido de cocción de la pechuga</li></ul><div><br></div>', '<div><strong>paso 1</strong><br>Para cocinar el pollo: en una olla de fondo alto poner la pechuga de pollo, el sobre de CALDO DE GALLINA MAGGI® Desmenuzado y el agua. Llevar a fuego medio tapado y dejar por 15 minutos o hasta que la pechuga esté bien cocinada, retirar del fuego, sacar la pechuga y dejar enfriar para desmechar. Reservar el líquido donde se preparó la pechuga, ya que sirve como base para preparar el arroz.</div><div><strong>paso 2</strong><br>Para preparar el arroz: en una olla de fondo alto poner el aceite y calentar a fuego medio por 3 minutos, sofreír la cebolla cabezona, el tomate, el pimentón, el ajo, la arveja, la zanahoria; añadir el NATURISIMO MAGGI®, mezclar bien para integrar. Por último, agregar el arroz y la taza y media del líquido de cocción de la pechuga que estaba reservado.</div><div><strong>paso 3</strong><br>Cocinar el arroz a fuego medio hasta que absorba todo el líquido, en ese momento agregar el pollo desmechado, dejar encima sin revolver, bajar el fuego a mínimo, tapar y dejar cocinar por 30 minutos más hasta que el arroz y los vegetales estén blanditos.</div><div><strong>paso 4</strong><br>Cuando el arroz y los vegetales estén bien cocinados; retirar del fuego y revolver para mezclar el arroz con el pollo.</div><div><strong>paso 5</strong><br>Servir el arroz en porciones iguales y acompañar con rodajas de tomate, tiras de lechuga y trozos de aguacate.</div><div><br></div>', 'images/recetas/nw8hA0IUdS8vgQgYAdZWBcb9428NyLUc46dZBuM5.jpeg', 1, 1, '2020-09-03 09:51:54', '2020-09-04 08:46:42'),
(5, 'Arroz con leche', '<ul><li>1 1/2 tazas de agua</li><li>1 (200g) taza de arroz</li><li>1 (5g) astilla de canela</li><li>2 (500ml) tazas de leche</li><li>1 (168g) taza de LECHE CONDENSADA LA LECHERA®</li><li>1/2 (120g) taza de CREMA DE LECHE NESTLÉ®</li><li>2 (30g) cucharadas de uvas pasas</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>En una olla de fondo alto a fuego bajo poner el agua, la astilla de canela y el arroz, cocinar por 15 minutos o hasta que absorba la mayor parte del líquido.</div><div><strong>PASO 2</strong><br>Agregar la leche y con una cuchara revolver constantemente.</div><div><strong>PASO 3</strong><br>Añadir la LECHE CONDENSADA LA LECHERA® y seguir revolviendo hasta que el arroz ablande y tome una consistencia cremosa.</div><div><strong>PASO 4</strong><br>Adicionar la CREMA DE LECHE NESTLÉ® y cocinar sin dejar de revolver por 4 minutos más.</div><div><strong>PASO 5</strong><br>Por último, agregar las uvas pasas y revolver para integrar, apagar el fuego y retirar la olla.</div><div><strong>PASO 6</strong><br>Servir el arroz caliente o frío según el gusto, en 8 porciones iguales. Sí desea, puede espolvorear canela molida por encima.</div><div><br></div>', 'images/recetas/Yonadlc9UuvV7AAfh3zehYB4rtwKLgXZ4lLASQTc.jpeg', 1, 4, '2020-09-03 09:53:18', '2020-09-04 08:47:09'),
(8, 'Ensalada especial', '<ul><li>1 Pechuga de pollo</li><li>1 Chorizo</li><li>1 Cucharada de Sazonador MAGGI® Sazonatodo</li><li>8 Papas cocidas y cortadas en cuadros</li><li>1 Taza de champiñones cortados en cuartos</li><li>½ Taza de arvejas frescas</li><li>½ Taza de habichuelas cortadas</li><li>2 Tazas de agua</li><li>1 Cubo de Caldo de verduras MAGGI® DOBLE GUSTO®</li><li>1 Taza de tomates Cherry cortados por mitad</li><li>1 Sobre de crema champiñones MAGGI®</li><li>1 Lata pequeña (32gr) de Crema de Leche NESTLÉ® Light</li><li>4 Cucharadas de leche en polvo KLIM® Fortificada preparadas en 1 1/2 de taza de agua</li><li>4 Cucharadas de mayonesa baja en grasa</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>Coloque la pechuga en agua con el Sazonador MAGGI® Sazonatodo, a fuego medio durante 20 minutos. Retire del fuego y corte en cuadros.</div><div><strong>PASO 2</strong><br>Coloque en una sartén a fuego medio el chorizo, con media cucharadita de agua. Cocine hasta que dore. Reserv</div><div><strong>PASO 3</strong><br>Cocine las habichuelas y las arvejas en el agua con el Caldo de verduras MAGGI® DOBLE GUSTO®</div><div><strong>PASO 4</strong><br>Disolver la Crema champiñones MAGGI® en la leche KLIM® llevar al fuego hasta que hierva y espese.</div><div><strong>PASO 5</strong><br>Apagando el fuego se agregue la Crema de Leche NESTLÉ® Light y la mayonesa a la preparación anterior mezclar bien y dejar enfriar.</div><div><strong>PASO 6</strong><br>Mezcle las verduras con la papa, la pechuga de pollo, el chorizo, el tomate cherry y los champiñones. Sirva enseguida.</div><div><br></div>', 'images/recetas/dnOyLvDjwIcNXTp3kSTXfjwxPIuPmbHnxePsXNdS.jpeg', 2, 7, '2020-09-03 14:21:15', '2020-09-04 08:49:11'),
(9, 'Mousse de maracuyá', '<ul><li>4 (30g) Galletas DORE® trituradas</li><li>1 1/2 (21g) cucharada de mantequilla derretida</li><li>5 (75g) cucharadas de LECHE CONDENSADA LA LECHERA® Light</li><li>½ (125g) taza de pulpa maracuyá sin pepa</li><li>3 (43g) cucharadas de queso crema bajo en grasa</li><li>3 (45g) cucharadas de CREMA DE LECHE NESTLE® Light</li><li>½ (2g) cucharadita de esencia de vainilla</li><li>1 1/2 (10g) sobre de gelatina sin sabor</li><li>2 cucharadas de agua</li></ul><div><br></div>', '<div><br><strong>PASO 1</strong><br>En un tazón mezclar la Galletas DORE® y la mantequilla derretida, mezclar hasta integrar bien, cubrir con la galleta la base de un molde pequeño; con las manos o una cuchara hacer presión para que se pegue bien al molde. Llevar al congelador por 10 minutos.</div><div><strong>PASO 2</strong><br>Aparte licuar la LECHE CONDENSADA LA LECHERA®, la pulpa de maracuyá, el queso crema, la CREMA DE LECHE NESTLE®Light y la esencia de vainilla a velocidad alta para integrar bien.</div><div><strong>PASO 3</strong><br>Por último, en un tazón pequeño disolver la gelatina en el agua tibia, mezclar hasta que no tenga grumos, añadir a la licuadora; licuar hasta integrar.</div><div><strong>PASO 4</strong><br>Retirar el molde del congelador y rellenar con la mezcla, tratando de que quede bien distribuida.</div><div><strong>PASO 5</strong><br>Llevar el molde al refrigerador por 3 horas o hasta que cuaje bien.</div><div><strong>PASO 6</strong><br>Pasado el tiempo de frío, retirar el molde del congelador, porcionar en partes iguales y servir.</div><div><br></div>', 'images/recetas/P9AASHei5JPshPlEwWGSRR9VywEhTIePYCHrZGvY.jpeg', 2, 4, '2020-09-03 14:23:22', '2020-09-04 08:49:27'),
(10, 'Hamburguesa de pollo', '<ul><li>2 (400g) tazas de pechuga de pollo molida</li><li>1 (6g) cucharadita de NATURISIMO MAGGI®</li><li>2 (28g) cucharadas de aceite</li><li>1 (30g) taza de cereal FITNESS® original triturado</li><li>4 (120g) tajadas de queso mozzarella</li><li>4 (200g) panes medianos de hamburguesa</li><li>2 (30g) cucharadas de CREMA DE LECHE NESTLÉ®</li><li>1 (12g) cucharada de mayonesa</li><li>4 (32g) hojas de lechuga</li><li>1 (123g) tomate mediano cortado en rodajas delgadas</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>En un recipiente hondo mezclar el pollo molido, el NATURISIMO MAGGI® y el cereal FITNESS® original triturado; con las manos mezclar hasta integrar bien. Formar 4 carnes de hamburguesa en partes iguales.</div><div><strong>PASO 2</strong><br>En una sartén a fuego medio calentar el aceite por 3 minutos, añadir la carne de hamburguesa de pollo y cocinar durante 7 minutos por cada lado o hasta que estén bien cocinadas y doradas. Una vez estén listas, bajar el fuego y poner una tajada de queso encima de cada una, hasta que se derrita un poco.</div><div><strong>PASO 3</strong><br>En un tazón pequeño mezclar la CREMA DE LECHE NESTLÉ® y la mayonesa. Untar cada pan con un poco de la mezcla y armar las hamburguesas poniendo encima del pan dos rodajas de tomate, una hoja de lechuga y la hamburguesa de pollo con el queso.</div><div><br></div>', 'images/recetas/JrreMLpzUPpqbwd8D1JTqgjNjDIdZjixfQzz8BZN.jpeg', 2, 5, '2020-09-03 14:25:27', '2020-09-04 08:49:45'),
(11, 'Carne de res al sartén', '<ul><li>6 Porciones de carne para asar de 110 gramos cada una</li><li>2 Cucharadas de aceite</li><li>1 Sobre de caldo de costilla con especias desmenuzado MAGGI®</li><li>1 Gajo de cebolla larga cortada en trozos medianos</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>Marine la carne con el contenido del sobre de Caldo de costilla con especias desmenuzado MAGGI® y la cebolla.</div><div><strong>PASO 2</strong><br>Reservelo durante 10 minutos en la nevera.</div><div><strong>PASO 3</strong><br>Caliente el aceite en una sartén o parrilla y deje asar la carne hasta que esté dorada y al gusto.</div><div><strong>PASO 4</strong><br>Puede acompañar con una porción de ensalada.</div><div><br></div>', 'images/recetas/vSMbGMl6PgvB8RYfi4g0Zbhd8h3tIngRwTjZsmAd.jpeg', 2, 6, '2020-09-03 14:27:01', '2020-09-04 08:50:06'),
(12, 'Burrito colombiano de pollo', '<ul><li>¼ Pechuga de pollo cocinada y desmenuzada</li><li>1 Taza de agua</li><li>1 Cucharadita de sazonador MAGGI® SAZONATODO</li><li>1 Tortilla de harina de trigo</li><li>1 Hoja de lechuga crespa</li><li>¼ Taza de queso mozzarella rallado</li><li>1 Cucharada de frijol refrito</li><li>1 Rodaja de aguacate finamente picado</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>Cocine la pechuga en 1 taza de agua con el sazonador MAGGI® SAZONATODO por 10 minutos, retire del agua, deje enfriar y desmeche.</div><div><strong>PASO 2</strong><br>Caliente la tortilla en una sartén de teflón pequeña.</div><div><strong>PASO 3</strong><br>Retire la tortilla y agregue la lechuga, el pollo, el queso, los frijoles y el aguacate.</div><div><strong>PASO 4</strong><br>Doble la tortilla. Si no se sujeta, use un palillo.</div><div><strong>PASO 5</strong><br>Parta la tortilla en dos partes.</div><div><strong>ACOMPAÑAMIENTO</strong><br>Acompañe el burrito caliente con un poco de crema agria, mango en julianas y un vaso de MILO</div><div><br></div>', 'images/recetas/zyd98uid4zT3GwP2sathipAH4gmnbDOG21Qh7JiY.jpeg', 2, 1, '2020-09-03 14:35:39', '2020-09-04 08:50:21'),
(13, 'Ensalada de mango', '<ul><li>1 Sobre de caldo de gallina con especias desmenuzada MAGGI®</li><li>2 Cucharadas de aceite de oliva</li><li>½ Pimentón rojo pequeño cortado en tiras</li><li>½ Pimentón verde pequeño cortado en tiras</li><li>2 Cucharada de cebolla cabezona picada</li><li>1 Cucharadita de estragón finamente picado</li><li>1 Taza de mango maduro pelado y cortado en cuadritos</li><li>¼ Lechuga lavada y cortada en trozos</li><li>¼ Taza de vino blanco</li><li>1 Cucharada Vinagre Balsámico</li><li>1 Cucharadita de cilantro finamente picado</li><li>1 Cucharadita de pimienta blanca</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>En una sartén con el aceite, sofría los pimentones y la cebolla por 3 minutos.</div><div><strong>PASO 2</strong><br>Retire del fuego y deje enfriar.</div><div><strong>PASO 3</strong><br>Forme la ensalada con el mango, la lechuga y los pimentones.</div><div><strong>PASO 4</strong><br>Aparte, mezcle los ingredientes restantes.</div><div><strong>PASO 5</strong><br>Sirva la ensalada acompañada de la salsa.</div><div><br></div>', 'images/recetas/NxVEMnePNB5SYZYY1XRHetWWgRnt2wQyzXD65Wu4.jpeg', 1, 7, '2020-09-03 14:38:22', '2020-09-04 08:47:28'),
(14, 'Omelette de claras con vegetales', '<ul><li>4 (80g) claras de huevo</li><li>1 (6g) cucharadita de SAZONADOR NATURISIMO MAGGI®</li><li>1 (14g) cucharada de aceite</li><li>1 (30g) taza de hojas de espinaca</li><li>1 (70g) taza de champiñones tajados</li><li>1 (118g) tomate fresco, cortado en cubos pequeños</li></ul><div><br></div>', '<div><strong>PASO 1</strong><br>En un recipiente hondo batir las claras ligeramente con un batidor de mano o tenedor, agregar el SAZONADOR NATURISIMO MAGGI® seguir batiendo hasta integrar bien.</div><div><strong>PASO 2</strong><br>En una sartén a fuego medio calentar el aceite por 3 minutos, saltear las espinacas, los champiñones y el tomate por 4 minutos.</div><div><strong>PASO 3</strong><br>En la misma sartén, agregar las claras de huevo, cocinar revolviendo con una espátula hasta que compacten pero no estén totalmente cocinadas, bajar el fuego y dejar que la omelette se termine de cocinar sin revolver.</div><div><strong>PASO 4</strong><br>Doblar la omellete a la mitad.<br>Porcionar y servir.</div><div><br></div>', 'images/recetas/05Q9ktkgYtXUtuiOxbPMr81UemRaFvPLNMMQ8caM.jpeg', 1, 7, '2020-09-06 11:22:06', '2020-09-06 11:22:06');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;